#!/bin/sh
#
#  .git/hooks/pre-commit
#
if [[ $(gci diff .) ]]; then
  echo '💥 Lint error: gci'
  exit 1
fi

if [[ $(goimports -d .) ]]; then
  echo '💥 Lint error: goimports'
  exit 1
fi

# Generate documentation
sh ./scripts/generate_docs.sh

git add USAGE.md
